version: '3.8'
services:
  samu3le_frontend_cargofive:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    container_name: samu3le_frontend_cargofive
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
